[package]
name = "parametrik_cli"
version = "0.1.0"
authors = ["Scott Trinh <scott@scotttrinh.com>"]
edition = "2018"

[[bin]]
bench = false
path = "src/main.rs"
name = "para"

[dependencies]
reqwest = "0.9"
structopt = "0.3"
dialoguer = "0.5"
serde = "1.0"
serde_json = "1.0"
