[package]
name = "parametrik_cli"
version = "0.1.0"
authors = ["Scott Trinh <scott@scotttrinh.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parametrik_data = { path = "../data" }
structopt = "0.3"
